### PR TITLE
Add vmprof

### PR DESCRIPTION
**Pull request by nctl144**
I added vmprof command line option to the project. Currently it only supports 3 benchmarkers, which are cssbench, xpathbench and linkextractor. I will add more soon! Let me know what you guys think :) #21

### CODE REVIEW

**Comment by lopuhin** [comment]
@nctl144 nice! Could you please also update the docs with a short description of what would happen? (it prints the uploaded URL, right?). I wonder if it's possible to add a ``--vmprof`` option that would work for all benchmarks, instead of listing them in ``vmprof`` command?

**Comment by nctl144** [comment]
> I wonder if it's possible to add a --vmprof option that would work for all benchmarks, instead of listing them in vmprof command?

I thought of doing that too, but the option in **click** just has the function to pass arguments to the commands (I found the information [here](http://click.pocoo.org/5/options/). So I think it would be the best to make another command for this task!
I will update the docs asap :)

**Comment by nctl144** [comment]
Hey @lopuhin , I have updated the doc for this PR. The reason why I put this PR command and option together in the beginning is I don't want this vmprof command to be mixed with other benchmarkers command. But this approach does not show the option's help text in the **scrapy-bench --help** command since its "--bench" option is not in **cli** group.
However, after trying to reorganize the code, I realized that it's okay if the user try to type some invalid option in the command, like **scrapy-bench --bench xpathbench bookworm**. In this case, the --bench option does not affect the command at all. Therefore, I decided to go for this approach, which is putting everything in its place to match other commands' code.
What do you think? :)

**Comment by lopuhin** [comment]
Thanks, this does make sense @nctl144 :) Sorry that I didn't make my idea clear from the start: I mean that an ideal API will look like ``scrapy-bench xpathbench --vmprof ``, but I understand that this API requires more work to implement (I think it could be implemented in ``calculate`` function, but needs a slightly different format of providing the benchmark arguments). If you want to do it this way, we can discuss the steps to do it if you want. Or if you are happy with the current way, I'm fine with merging it as is, the only nitpick I have is to remove cssbench default from vmprof command, as it seems strange to make one benchmark better than others :)

**Comment by nctl144** [comment]
@lopuhin Ohh I got your point now. It just makes more sense to make vmprof into an option, just like the "upload-result" one. I just made vmprof into an option so that when users state --vmprof in their command, the current benchmarker will trigger the profiling function. 
Thank you for clarifying that. It made the command line much cleaner that way :)

**Comment by lopuhin** [comment]
Looks great, thanks! 👍 

> In my recent commit, I know that I stated the benchmarker = '' variable many times since that is the only way that I could came up with on retrieving the current command name. But if you have some idea on how to improve it, I will work on that asap :)

I think it can be improved in the following way: right now we pass both ``arg`` (e.g. ``"python cssbench.py"``), and the name of benchmark, and then convert it back into a python file. Instead it seems possible to pass the name of the python file + any options if needed as ``arg``: e.g. ``cssbench.py`` for cssbench, or ``"%s crawl followall -o items.csv -a book_url=%s" % (scrapy_path, obj.book_url)`` in case of bookworm spider, where ``scrapy_path`` is output of `which scrapy`. Then in the calculator function it will be run as either ``python {arg}``, or as ``python -m vmprof {arg}`` - I think it makes more sense than running the benchmark twice as done currently. This will enable vmprof support for bookworm and other commands as well.

**Comment by nctl144** [comment]
Hey @lopuhin , thank you so much for showing me that 😃😃. I actually didn't think of doing it that way and now I know that we can run python libraries with python command (I actually didn't know beforehand). I just fixed this PR code to your suggestion and it works really fine. 

But please let me know if there is anything that can be improved :) I really enjoy contributing to scrapy so far!

**Comment by lopuhin** [comment]
Looks great! I think only one issue is left - I tried running ``scrapy-bench bookworm`` and it didn't work for me (tests didn't catch it as they don't run it yet). I think the reason is that ``os.path.dirname(scrapy.__file__)`` gives location of the scrapy package (for me it's ``/Users/kostia/shub/scrapy-bench/venv/lib/python3.6/site-packages/scrapy``), while we want the location of the scrapy command (for me it's ``/Users/kostia/shub/scrapy-bench/venv/bin/scrapy``). I don't know offhand how to get it, except for using ``which`` command which would make it non-portable. But I thought there is another way around - if you check the code of the scrapy command, it's very short and I think the only bit we need is this:
```
import sys

from scrapy.cmdline import execute

if __name__ == '__main__':
    sys.exit(execute())
```
so maybe instead of looking for the path to scrapy command, it will be possible to create a local file that would start crawling, and use it instead.

**Comment by nctl144** [comment]
Hey @lopuhin , thank you so much for showing me that **hack**. I didn't realize that could happen since I installed only Scrapy on my virtualenv. Learned a lot from this PR!

**Comment by nctl144** [comment]
I have tested this PR and I think it is ready @lopuhin. When you have time, can you please take a look at it for me? Thank you! :)

**Comment by lopuhin** [comment]
@nctl144 looks great, thanks a lot! 👍

**Comment by nctl144** [comment]
Thank you :)

**Pull request merged**
